### ISSUE TITLE
המון תודה! וקצת באגים

### ISSUE THREAD

**Issue by Oref1995** [Vladimir-pa/Degree-Planer#1]
קצת באגים שראיתי ממש בשימוש הראשוני:

- כתוב אצלי "טור מאנגלית" במקום פטור
- יש קורסים שהוא לא מכניס להם נק"ז (כותב 0) למשל אבולוציה והתקשורת בעידן המידע
- יש קריסה כשמסמנים בדיקת קדמים/צמדים

![image](https://user-images.githubusercontent.com/50577017/60769507-5d967680-a0d9-11e9-8645-388bd2fa976e.png)

![image](https://user-images.githubusercontent.com/50577017/60769514-71da7380-a0d9-11e9-8186-1c3c27a8d816.png)

אני אמשיך לעבוד עם זה ואעדכן,
ממש תודה רעיון מעולה!!!

**Comment by Krumpet** [comment]
If the data on UG doesn't contain number of points for a course, it can be found on the graduate website, maybe use this to get the number of points?

**Comment by Mitnitsky** [comment]
Hey thank you guys for the review, can you specify the url of the graduate website containing the relevant information ?

**Comment by Krumpet** [comment]
See here for an example: [digital systems page in graduate website](http://www.graduate.technion.ac.il/Subjects.Heb/?Sub=234145)

I already have a parser for that page (which extracts all course info) in my repo, here's a link to the relevant file: [graduate parser](https://github.com/Krumpet/ProjectKdam/blob/master/src/GraduateParser.py)

**Comment by Mitnitsky** [comment]
Fixed the typo(actually it was a margin problem), i've wrote the parser to try fetch the course points from the graduates web site if there is no information on the UG.
Both the change are on development branch feel free to test it
