### ISSUE TITLE
Support course exemption

### ISSUE THREAD

**Issue by TalSk** [Vladimir-pa/Degree-Planer#3]
Hi, I would like to see an option to mark a course as exempted.
Right now you have to input a grade between 1 and 100 for a course to be included in the calculation, which affects your overall grade, whereas normal exempted courses (like those done in other universities) won't.
I tried meddling myself with the Qt code, but both lack of knowledge in your code and Qt in general I couldn't add another column with a tick box to every course.
So I'd love that it will be implemented by someone else, or get some direction on how to do it, and I'll do a pull request.

Thanks, and good execution on an amazing idea!

**Comment by Mitnitsky** [comment]
I don't really think there is a nice way to fit the exemption check in the table because the scaling of the QTable widget is a mess, there is one appropriate way i thought of to mark a course as exempted i could add a grade of -1 to the grades range but that won't intuitive to the users

**Comment by Mitnitsky** [comment]
Another solution is to add an Exemption category to the combo box in the table, if you find that appropriate tell me :)

**Comment by TalSk** [comment]
Yeah, the second solution is what I somewhat managed to do myself, just for testing and playing around with the app, you're more than welcome to add this. Thank you :)

**Comment by Mitnitsky** [comment]
Implemented on Development branch , feel free to try it :)

**Comment by TalSk** [comment]
Just leaving a comment to say that it works great (apart that now you "don't know" if it's mandatory, A list, B list and such, so it requires manual subtraction)

**Comment by Mitnitsky** [comment]
Is it possible to get an exemption on a a/b list course?

**Comment by TalSk** [comment]
Personally all the courses I had exempted are mandatory, but I do know of people that have some from the a/b list.
